name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/be_db_dl:latest ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/be_db_dl:latest

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/be_db_dl:latest
            docker stop backend_app || true
            docker rm backend_app || true
            docker run -d -p 3030:3000 --name backend_app ${{ secrets.DOCKERHUB_USERNAME }}/be_db_dl:latest
